spring:
  application:
    name: shoppapp
  datasource:
    url: ${STRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/shopapp?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${MYSQL_ROOT_PASSWORD:}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      #ddl-auto: validate
      #hibernate sẽ không tạo, sửa đổi hoặc xóa bất kỳ bảng nào
      #validate thường được sử dụng trong môi trường production
      #Nếu có sự khác biệt giữa cấu trúc database và các entity
      #Lỗi sẽ được hiển thị và yêu cầu sửa đổi cấu trúc database một cách thủ công
    
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  messages:
    basename: i18n/messages
    encoding: UTF-8
    default-locale: en
  # flyway -> Migration
  # Đường dẫn tới thư mục chứa các script flyway
  flyway:
    locations: classpath:/db/migration,classpath:/dev/db/migration
    # Phiên bản baseline sẽ là 1 và không thực hiện bất cứ thay đổi nào trong db
    baseline-on-migrate: true
    baseline-version: 0
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
# port
server:
  port: 8080
api:
  prefix: /api/v1
jwt:
  expiration: 2592000  # 30 days = 30 * 24 * 60 *60
  secretKey: 6QljiUkU0sXBCBy+YJ2YC4Sk/Lqjro/RNqQgGw5KLOI=

logging:
  level:
    org:
      springframework.security: DEBUG
# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
  show-actuator: true
# health check
management:
  endpoint:
    health:
      show-details:always
  endpoints:
    web:
      base-path: /api/v1/actuator
      exposure:
        #include: "health"
        include: "health, info"
